---
services:
  mcp-server:
    build:
      context: .
      args:
        PYTHONIMAGEVERSION: ${PYTHONIMAGEVERSION:-3.13-slim}
    container_name: ${CONTAINERNAME:-mcp-server}
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      # Host kubeconfig and Minikube certs
      - ${USERPROFILE:-$HOME}/.kube/config:/root/.kube/config:ro
      - ${USERPROFILE:-$HOME}/.minikube:/root/.minikube:ro
      # Optional Selenium artifacts
      - ./selenium_results:/app/selenium_results
    env_file:
      - ./.env
    environment:
      - KUBECONFIG=/root/.kube/config
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
